#!/usr/bin/env python3
"""Bounded source and private-symbol closure for the G3RCV1 codec leaf."""

from pathlib import Path

root = Path(__file__).resolve().parents[1]
closure_path = root / "native/g3r_record_codec_source_closure.txt"
closure = closure_path.read_text().splitlines()
expected = [
    "internal/c1/lib/c1_sha256.esk",
    "native/g3r_record_codec_extension.esk",
    "tests/g3r/record_codec_test.esk",
    "tests/g3r/record_codec_feature_off_test.esk",
    "tests/g3r/check_record_codec_oracle.py",
    "tests/q0/test_python_isolation.py",
    "scripts/check-g3r-record-codec.py",
    "scripts/test-g3r-record-codec.sh",
    "docs/g3/G3_R_RECORD_CODEC_LEAF.md",
    "native/g3r_record_codec_source_closure.txt",
]
assert closure == expected
assert all((root / path).is_file() for path in closure)

sha = (root / expected[0]).read_text()
source = (root / expected[1]).read_text()
fixture = (root / expected[2]).read_text()
off = (root / expected[3]).read_text()
runner = (root / "scripts/test-g3r-record-codec.sh").read_text()
assert "(define (c1-sha256 bytes)" in sha
assert "(define (g3r-record-encode!" in source
assert "(define (g3r-record-decode!" in source
assert "(define g3r-record-size 288)" in source
assert "(c1-sha256 (bytevector-copy staged 0 256))" in source
assert "(c1-sha256 (bytevector-copy source 0 256))" in source
assert source.index("(c1-sha256 (bytevector-copy staged 0 256))") < source.index(
    "(bytevector-copy! destination 0 staged 0 g3r-record-size)")
decode = source.split("(define (g3r-record-decode!", 1)[1]
assert decode.index("(g3r-record-fields? policy rng history") < decode.index(
    "(vector-copy! destination 0 staged 0 8)")
assert decode.count("(vector-copy! destination 0 staged 0 8)") == 1
assert "(vector-set! destination " not in decode
assert "(g3r-bytes=? source 224 expected-c2-digest 0 32)" in decode
assert "(g3r-zero-range? source 122 128)" in decode
assert "(= (bytevector-u8-ref source 121) 0)" in decode
assert "(>= eos -1) (<= eos 255)" in source
assert "(>= budget 0) (<= budget 1)" in source
assert "(= (vector-ref rng 0) 1)" in source
assert "(>= (vector-ref rng 1) 0)" in source
assert "(>= prompt 1) (<= prompt 2)" in source
assert "(or (= generated 0) (= (vector-ref policy 4) 1))" in source
assert "(load \"c1_sha256.esk\")" in fixture
assert "(load \"g3r_record_codec_extension.esk\")" in fixture
assert "(load \"g3r_record_codec_extension.esk\")" not in off
assert "G3R_VECTOR " in fixture and "G3-R record codec PASS:" in fixture
for phrase in ("reject torn checksum", "reject wrong authenticated C2 pair",
               "reject unused history slot", "reject bad policy after reseal",
               "reject RNG version", "reject impossible partition",
               "reject generated byte under budget zero",
               "failed whole-range publication leaves numeric destination intact"):
    assert phrase in fixture, phrase
for forbidden in ("checkpoint-load", "checkpoint-save", "generator-create",
                  "generator-generate!", "et_a2_", "et_i64_", "extern ",
                  "fopen", "(open ", "(read ", "(write "):
    assert forbidden not in source, forbidden
for name in ("g3r-record-encode!", "g3r-record-decode!"):
    assert all(
        name not in path.read_text(errors="ignore")
        for path in (root / "lib").rglob("*.esk")
    )
assert 'nm "$directory/$fixture"' in runner
assert "grep -F 'g3r-record-encode!'" in runner
assert "grep -F 'g3r-record-' \"$directory/off.symbols\"" in runner
assert "check_record_codec_oracle.py" in runner
assert "--strict-types --optimize 0 --no-stdlib" in runner
print("G3-R record codec static PASS")
